from flask import Flask, render_template, request, send_file
import os
import main  

# app = Flask(__name__)
app = Flask(__name__, static_folder="outputs", static_url_path="")

UPLOAD_FOLDER = "uploads"
OUTPUT_FOLDER = "outputs"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

@app.route("/")
def index():
    return render_template("index.html")

# @app.route("/upload", methods=["POST"])
# def upload():
#     file = request.files["image"]

#     if file.filename == "":
#         return "No file selected"

#     input_path = os.path.join(UPLOAD_FOLDER, file.filename)
#     file.save(input_path)

#     #  CALL YOUR EXISTING PIPELINE
#     main.main_with_path(input_path)

#     output_path = os.path.join(OUTPUT_FOLDER, "task7_pipeline_visualization.png")

#     return send_file(output_path, mimetype="image/png")

@app.route("/upload", methods=["POST"])
def upload():
    file = request.files["image"]

    if file.filename == "":
        return "No file selected"

    input_path = os.path.join(UPLOAD_FOLDER, file.filename)
    file.save(input_path)

    #  Run your pipeline
    main.main_with_path(input_path)

    # Output images (already generated by your pipeline)
    outputs = {
        "preprocessing": "task2_preprocessing.png",
        "enhancement": "task3_enhancement.png",
        "segmentation": "task4_segmentation.png",
        "features": "task5_features.png",
        "final": "task7_pipeline_visualization.png"
    }

    #  THIS LINE (VERY IMPORTANT)
    return render_template("result.html", outputs=outputs)

if __name__ == "__main__":
    app.run(debug=True)